#!/usr/bin/env node
/**
 * Detect a clap (sharp transient) in raw PCM audio files.
 *
 * Usage:
 *   node detect_clap.js <file1.pcm> [file2.pcm] [file3.pcm]
 *
 * Input: raw 16-bit signed little-endian PCM, 16kHz mono
 *        (generated by: ffmpeg -y -i video.mov -vn -t 60 -ar 16000 -ac 1 -f s16le -acodec pcm_s16le out.pcm)
 *
 * Output: JSON to stdout:
 *   [{ "file": "file1.pcm", "clapTimeSec": 3.412 }, ...]
 */

const fs = require('fs');
const path = require('path');

const SAMPLE_RATE = 16000;
const WINDOW_SAMPLES = 160; // 10ms at 16kHz
const HOP_SAMPLES = 80;    // 5ms hop (50% overlap)

function readPCM(filePath) {
  const buf = fs.readFileSync(filePath);
  const samples = new Float32Array(buf.length / 2);
  for (let i = 0; i < samples.length; i++) {
    samples[i] = buf.readInt16LE(i * 2) / 32768.0;
  }
  return samples;
}

function computeRMSEnvelope(samples) {
  const numFrames = Math.floor((samples.length - WINDOW_SAMPLES) / HOP_SAMPLES) + 1;
  const envelope = new Float32Array(numFrames);

  for (let f = 0; f < numFrames; f++) {
    const offset = f * HOP_SAMPLES;
    let sum = 0;
    for (let i = 0; i < WINDOW_SAMPLES; i++) {
      const s = samples[offset + i];
      sum += s * s;
    }
    envelope[f] = Math.sqrt(sum / WINDOW_SAMPLES);
  }
  return envelope;
}

function detectClap(samples) {
  const envelope = computeRMSEnvelope(samples);

  // Compute derivative (frame-to-frame RMS increase)
  const derivative = new Float32Array(envelope.length - 1);
  let maxDeriv = 0;
  for (let i = 0; i < derivative.length; i++) {
    derivative[i] = Math.max(0, envelope[i + 1] - envelope[i]);
    if (derivative[i] > maxDeriv) maxDeriv = derivative[i];
  }

  if (maxDeriv === 0) return null;

  // Find noise floor (median of first 1 second of RMS)
  const firstSecondFrames = Math.min(Math.floor(SAMPLE_RATE / HOP_SAMPLES), envelope.length);
  const sortedFirst = Array.from(envelope.slice(0, firstSecondFrames)).sort((a, b) => a - b);
  const noiseFloor = sortedFirst[Math.floor(sortedFirst.length * 0.9)] || 0.01;

  // Find first spike: derivative > 30% of max AND RMS > 3x noise floor
  const derivThreshold = maxDeriv * 0.3;
  const rmsThreshold = Math.max(noiseFloor * 3, 0.05);

  let clapFrame = -1;
  for (let i = 0; i < derivative.length; i++) {
    if (derivative[i] >= derivThreshold && envelope[i + 1] >= rmsThreshold) {
      clapFrame = i + 1;
      break;
    }
  }

  if (clapFrame < 0) return null;

  // Refine: find exact sample where amplitude first crosses 50% of local peak
  const frameStart = clapFrame * HOP_SAMPLES;
  const searchStart = Math.max(0, frameStart - WINDOW_SAMPLES);
  const searchEnd = Math.min(samples.length, frameStart + WINDOW_SAMPLES * 2);

  let localPeak = 0;
  for (let i = searchStart; i < searchEnd; i++) {
    const abs = Math.abs(samples[i]);
    if (abs > localPeak) localPeak = abs;
  }

  const crossingThreshold = localPeak * 0.5;
  let clapSample = frameStart;
  for (let i = searchStart; i < searchEnd; i++) {
    if (Math.abs(samples[i]) >= crossingThreshold) {
      clapSample = i;
      break;
    }
  }

  return clapSample / SAMPLE_RATE;
}

function main() {
  const files = process.argv.slice(2);
  if (files.length === 0) {
    console.error('Usage: node detect_clap.js <file1.pcm> [file2.pcm] [file3.pcm]');
    process.exit(1);
  }

  const results = files.map(f => {
    const samples = readPCM(f);
    const clapTimeSec = detectClap(samples);
    return { file: path.basename(f), clapTimeSec };
  });

  console.log(JSON.stringify(results, null, 2));
}

main();
